version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - phpfpm
    networks:
      - qrt

  phpfpm:
    build:
      context: docker/php
      dockerfile: Dockerfile
    expose:
      - 9000
    links:
      - mysql
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    tty: true
    stdin_open: true
    networks:
      - qrt

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - 127.0.0.1:8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 500000000
    networks:
      - qrt

  larnode:
    image: node:latest
    volumes:
      - './:/code'
    environment:
      - NODE_ENV=development
    entrypoint: /usr/bin/tail
    command: [ "-f", "/dev/null" ]
    networks:
      - qrt

  mysql:
    image: mysql:8
    ports:
      - 127.0.0.1:3306:3306
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: qrt
      MYSQL_USER: qrt
      MYSQL_PASSWORD: qrt
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - qrt

volumes:
  db_data:

networks:
  qrt:

